version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spark-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spark-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - spark-network

  spark-master:
    image: apache-spark:3.4.0
    container_name: spark-master
    ports:
      - "8080:8080" # Web UI Master
      - "7077:7077" # Spark Master Port
      - "9999:9999" # Port for socket Data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - spark-network

  spark-worker-a:
    image: apache-spark:3.4.0
    container_name: spark-worker-a
    ports:
      - "8081:8081" # Web UI Worker
      - "7000:7000" # Spark Worker Port
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - spark-network

  spark-worker-b:
    image: apache-spark:3.4.0
    container_name: spark-worker-b
    ports:
      - "8082:8081" # Web UI Worker
      - "7001:7000" # Spark Worker Port
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - spark-network

  data-generator:
    image: python:3.9
    container_name: data-generator
    volumes:
      - ./data-generator:/app
    working_dir: /app
    depends_on:
      - kafka
    entrypoint: [ "sh", "-c", "apt-get update && apt-get install -y netcat-openbsd && sh /app/wait-for-kafka.sh && pip install kafka-python && python data_generator.py" ]
    networks:
      - spark-network


networks:
  spark-network:
    name: spark-network
    driver: bridge
